### ISSUE TITLE
Everyone is logged out after deployment with this package

### ISSUE THREAD

**Issue by weerdm** [404labfr/laravel-impersonate#42]
Hi,

I used this package to create an impersonate feature. After i released this to production, suddenly everybody was logged out.

Regards,

Marcel

**Comment by MarceauKa** [comment]
Are you sure you're not resetting your APP_KEY when deploying?

**Comment by weerdm** [comment]
Nope, 100% sure I did not change any keys.

**Comment by nlehmanDLC** [comment]
I can confirm this just happened to me also.

**Comment by MarceauKa** [comment]
Please give us your Laravel version

**Comment by nlehmanDLC** [comment]
5.6.15

**Comment by nlehmanDLC** [comment]
Well, for me it is hard to replicate to test out.

What happened for me was I was already logged in (with remember me checked) to my production environment when I pushed this for the first time.  After it was deployed, I tried to navigate somewhere and it told me I was not logged in.  After I logged back in, everything worked perfectly.

I didn't verify if others were logged out like what @weerdm said.  It's not a big deal for me, I just thought I'd let you know it happened to someone else.

**Comment by weerdm** [comment]
Or just "whoever has used impersonation cannot stay logged in despite using the remember-me feature"?

Its seems like we are also experiencing this, after impersonating a user and switching back to the original user, the remember me does not work.

**Comment by Thibaud91** [comment]
Hello,
Same thing happen on Laravel 5.6.21, everyone is logged out after installing the package.

**Comment by divdax** [comment]
same problem here...

**Comment by gbrits** [comment]
Same thing happened to me, unfortunately removing the package didn't fix it for me - and now I can't log in anymore at all. I will note that I upgraded the Laravel Framework from 5.3.* to 5.5.* before installing the package, as it's a required dependancy - perhaps this was the similarity for others?

**Comment by drbyte** [comment]
Hmmm ... I've used this package on a project that started on 5.4 and upgraded to 5.5, and last month upgraded to 5.6 without any "everyone is logged out" or "nobody can log in" issues.

(It still kills the remember-me token after impersonating, but not the other symptoms posted here.)

**Comment by slano** [comment]
I can confirm this issue with both file and redis as session driver and Laravel version 5.5.44

1. Login to application
2. Install package using composer require
3. check the application - I'm not logged in anymore
4. Remove package using composer remove
5. check the application - I'm logged in

**Comment by MarceauKa** [comment]
See the [1.4](https://github.com/404labfr/laravel-impersonate/releases/tag/1.4.0)

**Comment by slano** [comment]
I can still reproduce the issue with Laravel 5.8.31 and laravel-impersonate 1.4

**Comment by MarceauKa** [comment]
Tell me more, can't reproduce.

**Comment by slano** [comment]
php 7.2.19
os: linux
laravel 5.8.31

1. composer create-project --prefer-dist laravel/laravel test 
2. cd test
3. touch database/database.sqlite
4. modify .env: DB_CONNECTION=sqlite, DB_DATABASE=/path/to/database/database.sqlite
5. php artisan make:auth
6. php artisan migrate
7. php artisan serve
8. go to browser, open app and register a user
9. in browser, login as a user
10. composer require lab404/laravel-impersonate
11. go to browser, refresh the page, user will be logged out
12. composer remove lab404/laravel-impersonate
13. go to browser, refresh the page, user will be logged in

**Comment by MarceauKa** [comment]
Ok, got it! In `HomeController` I tried `logger()->info('session', session()->all());`. When you login, require impersonate and then remove it a new `laravel_web_*` key appears, ignoring the existing one.

**Comment by slano** [comment]
Hmmm, a `laravel_web_*` key should be in the session. In my test case I have a `laravel_web_*` key in the session immediately after logging in vanilla laravel app (step 9), and the key doesn't change with requiring/removing impersonate package. I only lose "logged in state" after steps 10 until step 12.

**Comment by MarceauKa** [comment]
Closed for inactivity.
